### ISSUE TITLE
Your sample project

### ISSUE THREAD

**Issue by araeubig** [stripe-samples/terminal-apps-on-devices#48]
Thanks for your great "hint" how it would be possible to create a real standalone card reader. Actually i'am not really familiar in developing Android apps but i searched for working solutions to start thinking about a final solution for an existing erp- and accounting system in Switzerland and Germany.

You included some links to more in-depth informations about "apps on device", but all links are dead. Where could i get more informations or when will these links be live?

Thanks and Regards André

**Comment by mshafrir-stripe** [comment]
@araeubig the Stripe Apps on Devices program is currently in a private beta and the documentation is gated specifically for the users in the program. We're only allowing a select number of users in at this time. Those users must meet certain criteria to be considered for the beta. One of those criteria is having Android developers available and ready to build an app. We aim to make the documentation available to a broader set of users in 2024.

**Comment by araeubig** [comment]
> @araeubig the Stripe Apps on Devices program is currently in a private beta and the documentation is gated specifically for the users in the program. We're only allowing a select number of users in at this time. Those users must meet certain criteria to be considered for the beta. One of those criteria is having Android developers available and ready to build an app. We aim to make the documentation available to a broader set of users in 2024.

Thanks for your answer. We have one developer in the new team and is asked via the normal hotline many times for the S700 device to check mor ein depth the possibilities. Actually the concept is based on the WisePOS E.

How could we participate in the beta program?

Thanks for your answer.

PS: The system work which our solution should work has actually round about 70.000 user and the normal developers think for completely own solutions and not working with existing possibilities and not with stripe. But the system allows to use stripe (and a swiss payment provider too) and the easiest solution would be the custom "Apps-on-device" solution.
